#!/usr/bin/python

import json, requests, time
from prometheus_client import start_http_server, Gauge

gauge = Gauge('chia_price_usd', 'Current Chia price in USD')

def process_request():
  response = requests.get("https://api.coingecko.com/api/v3/simple/price?ids=chia&vs_currencies=USD")
  value = float(response.json()["chia"]["usd"])
  gauge.set(value)
                
if __name__ == '__main__':
  start_http_server(9444)
  while True:
    process_request()
    time.sleep(60)
